// Management-area icons: the NextAdmin kit's icon set (@tailgrids/icons) exposed
// under the names the screens already use, so call sites only change their import.
// A few icons have no tailgrids equivalent and fall back to lucide.
import type { ComponentType, SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement> & { size?: number }
export type LucideIcon = ComponentType<IconProps>

export {
  ErrorCircle as AlertCircle,
  InfoTriangle as AlertTriangle,
  ArrowDownward as ArrowDown,
  ArrowUpward as ArrowUp,
  ArrowLeft,
  ArrowRight,
  ArrowAngularTopRight as ArrowUpRight,
  CertificateBadge1 as Award,
  XmarkCircle as Ban,
  Bell1 as Bell,
  OpenBook as BookOpen,
  Book4 as BookOpenCheck,
  CalendarTime as CalendarClock,
  Calendar as CalendarDays,
  Calendar as CalendarPlus,
  Check,
  CheckCircle1 as CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Dollar as CircleDollarSign,
  CheckCircle1 as ClipboardCheck,
  FileTextMultiple as ClipboardList,
  ClockThree as Clock3,
  Copy1 as Copy,
  CreditCard,
  Eye,
  FileText as FileCheck2,
  FileText as FilePlus2,
  FileText,
  Funnel1 as Filter,
  InfoCircle as Info,
  Bank1 as Landmark,
  Layers2 as Layers3,
  DashboardSquare1 as LayoutDashboard,
  Reload as LoaderCircle,
  Locked3 as LockKeyhole,
  MapMarker5 as MapPin,
  Link1AngularRight as ExternalLink,
  MenuFriesLeft1 as List,
  Exit as LogOut,
  Envelope1 as Mail,
  Envelope1 as MailQuestion,
  MenuHamburger1 as Menu,
  MoonHalfLeft5 as Moon,
  MenuMeatballs1 as MoreHorizontal,
  Pencil1 as Pencil,
  Phone,
  Play as PlayCircle,
  Plus,
  Reload as RefreshCw,
  ArrowBothDirectionHorizontal2 as Repeat2,
  Search1 as Search,
  Send1 as Send,
  Gear1 as Settings,
  Phone as Smartphone,
  Sun1 as Sun,
  Trash1 as Trash2,
  UserCircle1 as UserCheck,
  UserPencil as UserCog,
  User2 as UserRound,
  UserMultiple1 as Users,
  Wallet2 as Wallet,
  Close as X,
} from '@tailgrids/icons'

// No tailgrids equivalent.
export { GripVertical, Save, ShieldAlert, UserPlus, UserRoundMinus } from 'lucide-react'
